services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      - frontend-pnpm-store:/pnpm/store

volumes:
  frontend-node-modules:
  frontend-pnpm-store: