FROM redis:7-alpine AS dev
# COPY redis.dev.conf /usr/local/etc/redis/redis.conf
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

FROM redis:7-alpine AS prod
# COPY redis.prod.conf /usr/local/etc/redis/redis.conf
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]